--SELECT * FROM ANIMALS;

-- DEFAULT VALUES
-- ALTER TABLE ANIMALS ADD COLUMN LAST_VACCINE DATE DEFAULT '2025-10-11';

-- CUSTOM RESULTS FROM TABLE WITH COLUMN NAMES
-- SELECT 10*AGE+5 AS RESULT_TOTAL, AGE+ANIMAL_ID AS "AGE + ID(NAME WITH WHITE SPOTS)" FROM ANIMALS;

-- FUNCTION TO LOWER AND TO UPPER
-- SELECT LOWER(BREED) AS BREED, UPPER(COLOR) AS COLOR FROM ANIMALS;

-- REGULAR EXPRASSIONS
-- "_" - OPTIONAL SYMBOLS
-- "%" - OPTIONAL QUANTITY OPTIONAL SYMBOLS (FROM 0)
-- "___" - 3 SYMBOLS
-- "A___" - ROW WITH 4 SYMBOLS FROM A
-- "A%" - OPTIONAL ROW FROM A
-- "%A%" - ROW WITH SYMBOL A

-- TEMPLATE FOR REGULAR EXPRASSIONS
-- SELECT * FROM ANIMALS;
-- SELECT * FROM ANIMALS WHERE BREED LIKE '___';
-- SELECT * FROM ANIMALS WHERE COLOR LIKE '%I%'; -- NON-SENSETIVE TO TEXT CASE

-- DATE
-- SELECT CURRENT_DATE - LAST_VACCINE FROM ANIMALS;
-- SELECT AGE(LAST_VACCINE) FROM ANIMALS;
-- SELECT LAST_VACCINE, EXTRACT(MONTH FROM LAST_VACCINE) AS "MONTH", EXTRACT(DAY FROM LAST_VACCINE) AS "DAY" FROM ANIMALS;

-- NEXT VACCINATION IN 6 MONTHS
-- SELECT LAST_VACCINE + INTERVAL '6 MONTHS' FROM ANIMALS;

-- SORT DATA BY GROUP DEPENDS ON OTHER COLUMNS
-- COUNT ANIMALS EACH TYPE
-- SELECT BREED, COUNT(*) FROM ANIMALS GROUP BY BREED
-- AGRIGATION FUNCTION - FUNCTION WITH 1 RESULT DEPENDS ON MANY PARAMETERS - SUM, MIN, MAX, AVG, COUNT
-- SELECT BREED, MIN(AGE), MAX(AGE), AVG(AGE) FROM ANIMALS GROUP BY BREED;











